#ifndef CELL_H
#define CELL_H
#include "position.h"
#include "piece.h"
#include "move.h"
#include "info.h"
#include "subject.h"
#include "state.h"

// A single square. It is a Subject so that displays (TextDisplay, GraphicsDisplay)
// can observe it and redraw themselves whenever the square changes.
// Legal moves are generated by Board, not by the individual cells.
class Cell : public Subject {
    Position position;
    Piece occupant;

    public:
    void Reset(); // helper function
    bool isProtected = false;
    Cell(); // default constructor
    Cell(Position position, Piece occupant);
    Position getPosition();
    Piece getPiece() const;
    void setPiece(Piece piece);
    std::vector <Move> getAllValidMoves();
    bool isOccupied();
    Info getInfo() const override;
    void notify(Subject &from) override;
    PieceType getPieceType() const;
    void setCell(Info info, State state);
};

#endif
