#ifndef CELL_H
#define CELL_H
#include "position.h"
#include "piece.h"
#include "move.h"
#include "info.h"
#include "subject.h"
#include "state.h"

// A single square. It is a Subject so that displays (TextDisplay, GraphicsDisplay)
// can observe it and redraw themselves whenever the square changes.
// Legal moves are generated by Board, not by the individual cells.
class Cell : public Subject {
    Position position;
    Piece occupant;

    public:
    Cell(); // default constructor - only for resizing in Board
    Cell(Position position, Piece occupant);
    Position getPosition() const;
    Piece getPiece() const;
    void setPiece(Piece piece);
    bool isOccupied() const;
    Info getInfo() const override;
    PieceType getPieceType() const;
    Colour getColour() const;
    void setCell(Info info, State state);
};

#endif
